version: '3.8'
services:
  app:
    build: .
    command: ["yarn", "start:dev"]
    env_file: .env
    depends_on:
      - redis
    ports:
      - '3002:3000'
    volumes:
      - ./:/app
      - ./templates:/templates
      - /app/node_modules
    
  redis:
    image: redis:alpine
    volumes:
      - redis:/data

volumes:
  redis:
    driver: local
